const branch = [
  'Arcades Branch',
  'Chambishi Branch',
  'Chingola Branch',
  'Chipata Branch',
  'Chisokone Branch',
  'Choma Branch',
  'Cosmopolitan Branch',
  'Eastpark Mall Branch',
  'Head Office',
  'Kabulonga Centre Branch',
  'Kafue River Branch',
  'Kabwata Branch',
  'Kabwe Branch',
  'Kafubu Branch',
  'Kitwe Branch',
  'Livingstone Branch',
  'Lumwana Branch',
  'Lusaka Industrial Branch',
  'Lusaka Main Branch',
  'Manda Hill Mall Branch',
  'Matero Branch',
  'Matero Branch',
  'Mazabuka Branch',
  'Mkushi Branch',
  'Mufulira Branch',
  'Mukuba Mall Branch',
  'Ndola Branch',
  'Solwezi Branch',
  'Soweto Branch',
  'Waterfalls Mall Branch',
  'Woodlans Mall Branch'
];
export default branch;
